# ruff: noqa
"""esquema inicial

Revision ID: 44bce45cbd5a
Revises:
Create Date: 2026-06-16 11:46:21.151407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44bce45cbd5a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factura_redireccion",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("numero_cliente", sa.String(), nullable=False),
        sa.Column("numero_contrato", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notificaciones_config",
        sa.Column("usuario_id", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("canal", sa.String(), nullable=False),
        sa.Column("habilitado", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("usuario_id", "tipo", "canal"),
    )
    op.create_table(
        "suministros",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("suministro_referencia", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consumo_diario",
        sa.Column("suministro_id", sa.String(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("kwh", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suministro_id"],
            ["suministros.id"],
        ),
        sa.PrimaryKeyConstraint("suministro_id", "fecha"),
    )
    op.create_table(
        "objetivo_consumo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("suministro_id", sa.String(), nullable=False),
        sa.Column("valor_kwh", sa.Float(), nullable=False),
        sa.Column("origen", sa.String(), nullable=False),
        sa.Column("vigente_desde", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suministro_id"],
            ["suministros.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proyeccion_mensual",
        sa.Column("suministro_id", sa.String(), nullable=False),
        sa.Column("mes", sa.Date(), nullable=False),
        sa.Column("metodo_aplicado", sa.String(), nullable=False),
        sa.Column("meses_usados_como_base", sa.Integer(), nullable=False),
        sa.Column("dias_usados_como_base", sa.Integer(), nullable=False),
        sa.Column("bandera_confianza", sa.String(), nullable=False),
        sa.Column("rango_inferior_kwh", sa.Float(), nullable=False),
        sa.Column("rango_superior_kwh", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suministro_id"],
            ["suministros.id"],
        ),
        sa.PrimaryKeyConstraint("suministro_id", "mes"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proyeccion_mensual")
    op.drop_table("objetivo_consumo")
    op.drop_table("consumo_diario")
    op.drop_table("suministros")
    op.drop_table("notificaciones_config")
    op.drop_table("factura_redireccion")
    # ### end Alembic commands ###
